links:
  - https://hnrss.org/best
  - https://ounapuu.ee/index.xml
  - https://feeds2.feedburner.com/TheArtOfManliness
  - https://lifehacker.com/feed/rss
  - https://www.entrepreneur.com/latest.rss
  - https://www.archanaskitchen.com/?format=feed&type=atom
  - https://feeds.feedburner.com/photofocus/pf
